### ISSUE TITLE
404 for the top 10 visited

### ISSUE THREAD

**Issue by davilious** [skuark/dsong-archive#7]
All content here gives a 404 error 😕

<img width="769" alt="Captura de pantalla 2021-02-04 a las 11 54 19" src="https://user-images.githubusercontent.com/950504/106883095-cdb71500-66df-11eb-8286-e9dbf0c87d7c.png">

**Comment by skuark** [comment]
@davilious Already fixed! 🥳 Thanks, bro!

https://5.dsong.es
